import fs from "node:fs";
import path from "node:path";
import { writeWorkbook } from "../src/reporting/workbook.js";

const onePixelPng = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z4mUAAAAASUVORK5CYII=",
  "base64"
);

const screenshotPath = path.join(process.cwd(), "artifacts", "screenshots", "phase1-fixture.png");
const reportPath = path.join(process.cwd(), "artifacts", "reports", "phase1-sample.xlsx");
fs.mkdirSync(path.dirname(screenshotPath), { recursive: true });
fs.writeFileSync(screenshotPath, onePixelPng);

await writeWorkbook(reportPath, [{
  findingId: "QAP-FRAMEWORK-001",
  module: "Framework",
  scenarioId: "PHASE1-SAMPLE",
  sourceClassification: "observed-application",
  category: "Functional Bug",
  severity: "Low",
  steps: "Generate and reopen the Phase 1 sample workbook.",
  expectedResult: "Nine ordered sheets and an embedded screenshot.",
  actualResult: "Sample generated by the reporting foundation.",
  uiEvidence: "Embedded fixture image",
  networkEvidence: "Not applicable",
  persistenceResult: "Not applicable",
  traceReference: "",
  productConfirmationStatus: "Not applicable"
}], screenshotPath);

process.stdout.write(`${reportPath}\n`);
